enum AdvertisingCampaign {
  ADVERTISING_CAMPAIGN_PARK_ENTRY_FREE = 0,
  ADVERTISING_CAMPAIGN_RIDE_FREE = 1,
  ADVERTISING_CAMPAIGN_PARK_ENTRY_HALF_PRICE = 2,
  ADVERTISING_CAMPAIGN_FOOD_OR_DRINK_FREE = 3,
  ADVERTISING_CAMPAIGN_PARK = 4,
  ADVERTISING_CAMPAIGN_RIDE = 5,
  //ADVERTISING_CAMPAIGN_COUNT = 6
}
